// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD7zO-fRNWS4rftcLM_siUzgPpq4RojMg',
    appId: '1:68187535877:web:db59c8c309408b9737ba6c',
    messagingSenderId: '68187535877',
    projectId: 'authentication-3490e',
    authDomain: 'authentication-3490e.firebaseapp.com',
    storageBucket: 'authentication-3490e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmM3mDqIkZ3fF8XMQnvpNhuMlDdjke_kc',
    appId: '1:68187535877:android:95789df99716d61037ba6c',
    messagingSenderId: '68187535877',
    projectId: 'authentication-3490e',
    storageBucket: 'authentication-3490e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe9micJaVjWpomS2krXif1QPjCLf3sMl8',
    appId: '1:68187535877:ios:aee67821a18fbc0a37ba6c',
    messagingSenderId: '68187535877',
    projectId: 'authentication-3490e',
    storageBucket: 'authentication-3490e.appspot.com',
    iosClientId: '68187535877-fkjk90ho54ds89pd7qm5r4d8gvg8pb39.apps.googleusercontent.com',
    iosBundleId: 'com.example.tugasAkhir',
  );
}
